### ISSUE TITLE
possible bug in answer

### ISSUE THREAD

**Issue by bootandy** [kjam/data-wrangling-pycon#8]
Hi I was working thru your example and noticed here:

https://github.com/kjam/data-wrangling-pycon/blob/0c31ffbe0a4dda422a46070ac1d963b6310b3926/books/pydata-examples/solutions/data_analysis_solution.py#L17

Shouldn't this line 

>  df.groupby('hour')['descendants'].transform(median)

be:

>  df.groupby('hour')['num_kids'].transform(median)

?

**Comment by kjam** [comment]
Thanks for the catch! It's now updated! :+1:
